### ISSUE TITLE
chef-server-ctl reconfigure fails on AWS hosts because node.fqdn is undefined

### ISSUE THREAD

**Issue by irvingpop** [opscode-cookbooks/delivery-cluster#120]
The nginx service is unable to start because its template depends on node.fqdn:  https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/templates/default/nginx/nginx.conf.erb#L98

but this is nil because:
```
root@ip-33-33-33-254:~# chef-shell 
loading configuration: none (standalone session)
Session type: standalone
Loading.done.

This is the chef-shell.
 Chef Version: 12.3.0
 http://www.chef.io/
 http://docs.chef.io/

run `help' for help, `exit' or ^D to quit.

Ohai2u!
chef > node.fqdn
NoMethodError: Undefined method or attribute `fqdn' on `node'
	from /opt/chef/embedded/apps/chef/lib/chef/node/attribute.rb:468:in `method_missing'
	from /opt/chef/embedded/apps/chef/lib/chef/node.rb:229:in `method_missing'
	from (irb):1
	from /opt/chef/embedded/apps/chef/lib/chef/shell.rb:76:in `block in start'
	from /opt/chef/embedded/apps/chef/lib/chef/shell.rb:75:in `catch'
	from /opt/chef/embedded/apps/chef/lib/chef/shell.rb:75:in `start'
	from /opt/chef/embedded/apps/chef/bin/chef-shell:37:in `<top (required)>'
	from /usr/bin/chef-shell:51:in `load'
	from /usr/bin/chef-shell:51:in `<main>'
chef > `hostname -f`
hostname: Name or service not known
 => "" 
```

In my experience you must set an FQDN before you can reconfigure successfully.

**Comment by afiune** [comment]
@irvingpop Ihave seen that, you need to add an entry to the `/etc/hosts`. it is a problem with how OHAI is trying to get the `fqdn` from the box.

**Comment by trickyearlobe** [comment]
Wouldn't it be better to fix Ohai ?
* ```hostname -f``` performs a reverse lookup (against /etc/hosts, DNS and NIS)
* ```hostname -A``` performs a reverse lookup, but for all interfaces (possibly returning multiple names)
* ```hostname```  with no params returns the configured hostname (without performing /etc/hosts, DNS or NIS lookups)

In pseudo code:

```ruby
def my_fqdn
  if shell("hostname -f").exitcode == 0
    return shell("hostname -f).output.chomp
  else
    return shell("hostname").output.chomp
  end
end
```

**Comment by afiune** [comment]
I kinda like the proposal from Mr @trickyearlobe ..

**Comment by irvingpop** [comment]
This issue is also being discussed in https://github.com/chef/chef-server/issues/21

For now we urgently need to get users unblocked who are trying this on aws
