### ISSUE TITLE
the delivery server doesn't run an apt-get update

### ISSUE THREAD

**Issue by cwebberOps** [opscode-cookbooks/delivery-cluster#128]
This may go in a different cookbook, but putting it here to track... we should ensure `apt-get update` gets run before we try to upgrade the delivery package

**Comment by afiune** [comment]
+1 on tracking this kind of things here! :smile:

**Comment by afiune** [comment]
Working on this now! :smile: cc/ @chef-delivery

**Comment by afiune** [comment]
Fixed with https://github.com/opscode-cookbooks/delivery-cluster/commit/f7178a6f9ea6f60dd6eb5ded533a750c6c5ea3c5
