### ISSUE TITLE
Customizable `delivery.rb` 

### ISSUE THREAD

**Issue by afiune** [opscode-cookbooks/delivery-cluster#134]
As a user I need to have a way to customize my `/etc/delivery/delivery.rb` so I don’t have to manually modify it and the delivery-cluster automation don’t override my manual configuration.

**Comment by stephenlauck** [comment]
@afiune should we just go ahead and deprecate chef-server-ingredient and use https://github.com/chef-cookbooks/chef-ingredient/blob/master/libraries/chef_ingredient_resource.rb#L29 ?

**Comment by afiune** [comment]
@stephenlauck Thats a good idea! But definitely a major change that we have to make a bunch of tests.. :smile: 

We'll get there though!

**Comment by afiune** [comment]
Fixed with https://github.com/opscode-cookbooks/delivery-cluster/commit/45d3dbb2a639c75f9e4a9a229f0fb64e240e2182
