### ISSUE TITLE
knife ssl fetch -c /var/opt/delivery/workspace/etc/delivery.rb fails during upgrade

### ISSUE THREAD

**Issue by mjohno** [opscode-cookbooks/delivery-cluster#143]
We ran the latest delivery cluster today (06/07/2014) and it was unable to upgrade our build nodes. The exact error is:
```
Ran knife ssl fetch -c /var/opt/delivery/workspace/etc/delivery.rb returned 100

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/delivery_build/recipes/workspace.rb
85: execute "fetch_ssl_certificate" do
86:   command "knife ssl fetch -c #{delivery_config}"
87:   not_if "knife ssl check -c #{delivery_config}"
88: end
89:
```

The contents of /var/opt/delivery/workspace/etc/delivery.rb is:
```ruby
current_dir = File.dirname(__FILE__)
log_location STDOUT
node_name "delivery"
client_key "#{current_dir}/delivery.pem"
trusted_certs_dir "/etc/chef/trusted_certs"
```

Could it be that delivery_build cookbook has been updated and the delivery.rb.erb template has been changed?

We are using the SSH driver.

**Comment by mjohno** [comment]
This is the diff of the delivery.rb.erb file within the delivery_build cookbook. I don't have permission to view it.

Cookbook version 0.2.8
```
current_dir = File.dirname(__FILE__)
<%
  config_hash = {
    :log_location => 'STDOUT',
    :node_name => '"delivery"',
    :client_key => '"#{current_dir}/delivery.pem"',
    :trusted_certs_dir => '"/etc/chef/trusted_certs"'
  }
-%>
<% config_hash.each do |config_key, value| -%>
<%= config_key %> <%= value %>
<% end -%>
<% Chef::Config.each do |config_key, value|
   unless config_hash.has_key?(config_key)-%>
<%= config_key %> <%= value.pretty_inspect %>
<% end
end -%>
```

Cookbook version 0.2.6
```
current_dir = File.dirname(__FILE__)
log_location      STDOUT
node_name         "delivery"
client_key        "#{current_dir}/delivery.pem"
trusted_certs_dir "/etc/chef/trusted_certs"
<%
%W{
  chef_server_url
  https_proxy
  https_proxy_pass
  https_proxy_user
  http_proxy
  http_proxy_pass
  http_proxy_user
  no_proxy
}.each do |config|
  if Chef::Config[config.to_sym]
%>
<%= config %> "<%= Chef::Config[config.to_sym] %>"
<% end
end -%>
```

**Comment by afiune** [comment]
@mjohno Apologize for the inconveniences. Although you mentioned something very important about the `delivery_build` cookbook, at first look it seems that is the problem since you have proxy settings that are not being laid down. For a quick **workaround** please use the old version `0.2.6` of the cookbook. 

Could you please help us providing the version of your delivery-server that you upgraded to? (from X to Y)

Thanks!

**Comment by mvillis** [comment]
Not 100% sure of what the version was before hand (it was pretty recent). It was current as at 28th June. The version we went to is 0.3.138

**Comment by afiune** [comment]
Thanks @mvillis that's enough information. Could you please try the workaround and let us know if that fixes your issue? :smile: cc/ @mjohno

**Comment by mvillis** [comment]
Rolled back to version 0.2.6 of the delivery_build cookbook and re-run the upgrade.
Workaround successfully applied.

```
[user@server delivery-cluster]$ knife cookbook delete delivery_build
Which version(s) do you want to delete?
1. delivery_build 0.2.8
2. delivery_build 0.2.6
3. delivery_build 0.2.5
4. delivery_build 0.2.4
5. delivery_build 0.2.0
6. delivery_build 0.1.7
7. delivery_build 0.1.5
8. All versions

1
Deleted cookbook[delivery_build][0.2.8]
```

**Comment by afiune** [comment]
Closing this since there is a workaround. We will let you know when there is a new version without the bug! Thank you for your feedback..

**Comment by afiune** [comment]
@mjohno @mvillis We have a recommendation for you guys. We would like you to validate that `delivery` is pointing to our `stable` repository in package cloud. The line is this one https://github.com/opscode-cookbooks/delivery-cluster/blob/master/attributes/default.rb#L134

Additionally check you environment file since this could be overwritten.. :smile:

**Comment by mjohno** [comment]
Hi @afiune. Thanks for the workaround. I just double checked and our attribute is the same as the one you posted. No explicit overrides in our environment config either (see our trello wall for the full environments file).

```
"delivery": {
  "host": "delivery.internal.corp",
  "fqdn": "delivery.internal.corp",
  "enterprise": "test",
  "version": "latest",
  "license_file": "/home/user/delivery-suncorp.license",
}
```

Could it be something to do with using the latest version for the delivery override_attribute within the environments file?

**Comment by afiune** [comment]
@mjohno Thank you for the confirmation! I don't think so. We will see on the next upgrade why you jumped to that buggy version of delivery that was not released to `stable`.. Please notify us when you are going to do this task to monitor.
