### ISSUE TITLE
Errno::EADDRINUSE error on `opscode-reporting-ctl reconfigure`

### ISSUE THREAD

**Issue by schisamo** [opscode-cookbooks/delivery-cluster#79]
Using the latest code I am consistently receiving the following failure when reporting is being configured:

```
[2015-04-22T01:59:51+00:00] ERROR: execute[opscode-reporting-ctl reconfigure] (chef-server-12::default line 22) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of opscode-reporting-ctl reconfigure ----
STDOUT: [2015-04-22T01:59:20+00:00] INFO: Starting chef-zero on port 8889 with repository at repository at /opt/opscode-reporting/embedded

  One version per cookbook

[2015-04-22T01:59:20+00:00] FATAL: Errno::EADDRINUSE: Address already in use - bind(2)
STDERR: the ffi-yajl and yajl-ruby gems have incompatible C libyajl libs and should not be loaded in the same Ruby VM
falling back to ffi which might work (or might not, no promises)
---- End output of opscode-reporting-ctl reconfigure ----
Ran opscode-reporting-ctl reconfigure returned 1
```

A larger stack trace is available here: https://gist.github.com/schisamo/9b05472f0467644cc479

This issue is caused by a [recent update in omnibus-ctl](https://github.com/chef/omnibus-ctl/pull/23) which was changed to use Chef Zero under the covers for the `reconfigure` subcommand. The easiest fix might be locking to a known working version of opscode-reporting that uses Chef Solo for it's reconfigure (vs Chef Zero). Once all projects update to use Chef 12.3.0 they can take advantage of [Socketless Chef Zero local mode](https://github.com/chef/chef/blob/master/RELEASE_NOTES.md#socketless-chef-zero-local-mode) which should make this issue go away.

/cc @opscode-cookbooks/delivery

**Comment by afiune** [comment]
Closing this since we have a permanent fix with https://github.com/opscode-cookbooks/delivery-cluster/commit/d848a8cb1c5f0aec4e518eba9622aadb1675e597
