### ISSUE TITLE
chef server / delivery api calls use IP unless you set fqdn in environment config

### ISSUE THREAD

**Issue by mvillis** [opscode-cookbooks/delivery-cluster#94]
*Environment:* RHEL 6.5
*Hostname var set:* True

During the install of chef delivery (```chef exec rake setup:cluster```) api calls to the chef server will use the IP address instead of the fqdn which causes certificate issues.
Post install, Chef Delivery's base url is the ip address of the chef delivery installer not the fqdn.

This is due to the installer setting the fqdn value for chef server and delivery to the ip address not the dns. 

Workaround is to set the fqdn for chef server and delivery in your environment config as below:
```
      "chef-server": {
        "existing": true,
        "host": "chfrd1.domain",
        "organization": "acme",
        "fqdn": "chfrd1.domain"
      },
```

```
      "delivery": {
        "host": "chfrd2.domain",
        "fqdn": "chfrd2.domain",
        "enterprise": "acme",
        "version": "0.3.31",
        "license_file": "/home/user/delivery-acme.license"
      },
```

**Comment by jonsmorrow** [comment]
This applies to all machines that have an nginx ui on them. so analytics, splunk, and soon supermarket.

**Comment by afiune** [comment]
That is the correct behavior. To use the FQDN just when you configure it but, it should also take the `host` attribute when we set it. Will work on that! :smile:
