### ISSUE TITLE
TESTING: We should have some

### ISSUE THREAD

**Issue by jonsmorrow** [opscode-cookbooks/delivery-cluster#97]
I wanted to file an issue to start a conversation around how do we test delivery-cluster. It has a ton of code now and is pretty critical so we should probably have test coverage. Being that this is a provisioning cookbook it feels weird in a sense to chef-spec cause those just become regression tests. Maybe there's value in that? But for all the library code I think we could probably unit test those well enough.

**Comment by afiune** [comment]
There was one issue for this.. :joy_cat: https://github.com/opscode-cookbooks/delivery-cluster/issues/2

**Comment by afiune** [comment]
There are already tests in place. 
https://github.com/opscode-cookbooks/delivery-cluster/tree/master/spec/unit/recipes
https://github.com/opscode-cookbooks/delivery-cluster/tree/master/spec/unit/libraries

Additionally @jonsmorrow has implemented `redpill` in delivery for a matrix testing.
https://github.com/opscode-cookbooks/delivery-cluster/tree/master/.delivery/build/cookbooks/delivery-red-pill

Whenever we add code we MUST add tests. 

Closing this :smile:
