### ISSUE TITLE
Destroy doesn't clean up cluster data

### ISSUE THREAD

**Issue by jonsmorrow** [opscode-cookbooks/delivery-cluster#99]
We should have a clean env after a destroy I think that should include cleaning our the local cluster data directories.

**Comment by afiune** [comment]
@jonsmorrow Uhmm I think it could be helpful but keep in mind delivery-cluster supports multiple clusters at the same time. So maybe not all of them since we could delete also keys from other clusters.. 

I can work on this..

**Comment by afiune** [comment]
fixed https://github.com/opscode-cookbooks/delivery-cluster/pull/112
